# YAML config file for StyleGAN2-ADA inversion

seed: null
image_path: data/pairs/sample_0_image.png
mask_path: data/pairs/sample_0_mask.png
save_folder: output/inversion_weights/sample_0
losses:
  - mse: 1
  - lpips: 1
  - clip:
      model: ViT-B/32
      weight: 0.5
      caption: A close-up portrait of a young woman wearing sun glasses.

verbose: true
device: cuda
num_steps: 100
learning_rate: 0.1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      losses.2.clip.weight: 0.05,0.1,0.2,0.5,1.0,2.0,5.0