# YAML config file for StyleGAN2-ADA inversion

seed: null
image_path: data/pairs/sample_0_image.png
mask_path: data/pairs/sample_0_mask.png
save_folder: output/inversion_seeds/sample_0
losses:
  - mse: 1
  - lpips: 1

verbose: true
device: cuda
num_steps: 100
learning_rate: 0.1

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +seed: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9